# Generated by Django 4.0.5 on 2022-06-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problem_name',
        ),
    ]
