# Generated by Django 4.0.5 on 2022-07-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0002_rename_problem_submission_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
